name: E2E
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - uses: actions/checkout@v4

      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile

      - name: Build Docker and download packages in parallel
        if: env.GIT_DIFF
        run: |
          set -e
          echo "Starting docker build and go mod download in parallel..."

          make docker-build-debug &
          PID1=$!

          make docker-build-hermes &
          PID2=$!

          go test -run=^$ ./tests/e2e/... &
          PID3=$!

          wait $PID1
          wait $PID2
          wait $PID3

          echo "All tasks completed."

      - name: Test E2E
        if: env.GIT_DIFF
        env:
          SKIP_IBC_TESTS: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
        run: make test-e2e