name: E2E
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-images:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: actions/checkout@v4

      - name: Set Docker Tag
        id: set-tag
        run: echo "tag=ci-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Docker Images
        run: make docker-build-all

      - name: Save Docker Images
        run: |
          mkdir -p docker
          docker save kiichain/kiichaind-e2e > docker/kiichain.tar
          docker save kiichain/hermes-e2e:1.0.0 > docker/hermes.tar

      - name: Upload Docker Images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: docker/

  test-e2e:
    runs-on: ubuntu-latest
    needs: build-images
    timeout-minutes: 45
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: actions/checkout@v4

      - name: Download Docker Images
        uses: actions/download-artifact@v4
        with:
          name: docker-images

      - name: Load Docker Images
        run: |
          docker load < docker/kiichain.tar
          docker load < docker/hermes.tar
      - name: Test E2E
        # if: env.GIT_DIFF
        run: SKIP_IBC_TESTS=true make test-e2e
      # - uses: technote-space/get-diff-action@v6.1.2
      #   id: git_diff
      #   with:
      #     PATTERNS: |
      #       **/*.go
      #       go.mod
      #       go.sum
      #       **/go.mod
      #       **/go.sum
      #       **/Makefile
      #       Makefile
