name: E2E
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: actions/checkout@v4

      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile

      - name: Build Docker Images
        if: env.GIT_DIFF
        run: make docker-build-all
      
      - name: Test E2E
        if: env.GIT_DIFF
        env:
          SKIP_IBC_TESTS: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
        run: make test-e2e
