name: Check Markdown links
# on: 
#   workflow_dispatch:
#   schedule: 
#     - cron: '* */24 * * *'
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          file-extension: ".md"